theme: jekyll-theme-minimal
title: Anurag Pallaprolu
description: Homepage.
logo: https://raw.githubusercontent.com/apallaprolu/apallaprolu.github.io/refs/heads/master/IMG-20241127-WA0002.jpg
google_analytics: UA-154973631-1
future: true
